BrowserCreativeNtlmBundle_main_login:
    pattern:   /login
    defaults:  { _controller: BrowserCreativeNtlmBundle:Security:login }

BrowserCreativeNtlmBundle_main_logincheck:
    pattern:   /login_check

BrowserCreativeNtlmBundle_main_logout:
    pattern:   /logout